# Generated by Django 4.1 on 2025-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="dishes/"),
        ),
    ]
