# Generated by Django 5.2.5 on 2025-08-26 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_ingredient_alter_dish_picture_dish_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="dish_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dishes",
                to="kitchen.dishtype",
            ),
        ),
    ]
